Avoiding profilings with no summarizations
It causes an error for trying to read a None path on GCP:

```
Traceback (most recent call last):
  File "/worker/services/notification/__init__.py", line 186, in notify_individual_notifier
    res = await notifier.notify(comparison)
  File "/worker/services/notification/notifiers/checks/checks_with_fallback.py", line 50, in notify
    res = await self._checks_notifier.notify(comparison)
  File "/worker/services/notification/notifiers/checks/base.py", line 169, in notify
    payload = await self.build_payload(filtered_comparison)
  File "/worker/services/notification/notifiers/checks/project.py", line 65, in build_payload
    message = await self.get_message(comparison, settings_to_be_used)
  File "/worker/services/notification/notifiers/checks/project.py", line 21, in get_message
    return await self.create_message(comparison, pull_dict, yaml_comment_settings)
  File "/worker/services/notification/notifiers/mixins/message.py", line 301, in create_message
    for line in section_writer.write_section(
  File "/worker/services/notification/notifiers/mixins/message.py", line 452, in write_section
    overlay = comparison.get_overlay(OverlayType.line_execution_count)
  File "/worker/services/comparison/__init__.py", line 154, in get_overlay
    return get_overlay(overlay_type, self, **kwargs)
  File "/worker/services/comparison/overlays/__init__.py", line 12, in get_overlay
    return CriticalPathOverlay.init_from_comparison(comparison, **kwargs)
  File "/worker/services/comparison/overlays/critical_path.py", line 44, in init_from_comparison
    critical_path_report=_load_critical_path_report(comparison),
  File "/worker/services/comparison/overlays/critical_path.py", line 26, in _load_critical_path_report
    comparison.get_archive_service().read_file(
  File "/worker/services/archive.py", line 205, in read_file
    contents = self.storage.read_file(self.root, path)
  File "/usr/local/lib/python3.8/site-packages/shared/storage/gcp.py", line 108, in read_file
    blob = self.get_blob(bucket_name, path)
  File "/usr/local/lib/python3.8/site-packages/shared/storage/gcp.py", line 29, in get_blob
    return storage.Blob(path, bucket)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 200, in __init__
    name = _bytes_to_unicode(name)
  File "/usr/local/lib/python3.8/site-packages/google/cloud/_helpers.py", line 389, in _bytes_to_unicode
    raise ValueError("%r could not be converted to unicode" % (value,))
ValueError: None could not be converted to unicode
```