Fix ci lint (#952)
* fix: update black version to 22.3.0

Circle CI jobs were failing with
ImportError: cannot import name '_unicodefun' from 'click'.

That was an error with the version of black and click.

* run black version 22.3.0 in codebase

* Revert "run black version 22.3.0 in codebase"

This reverts commit 85ca3bea35e48ee261dab2ec7a8b2aa54ee24ae9.
This is to run the proper command with --skip-magic-comma

* run black 22.3 with skip magic trailing comma

* remove -Iv option from make lint

* Change lint step executed in CI

The 2 steps executed in CI now are:
	* `pylint` from `make lint.ci` at the `pylint-django` job
	* `(black|isort) --check` from the `lint-isort` job.

Steps to run locally is `make lint`.