Fixing analystics version
Recently, on our upgrade session, we upgraded the package `analytics-python` from

```
analytics-python==1.3.0b1
```

to

```
analytics-python==1.3.0b3.dev0
```

which was the latest version of it.

We got the exception

```
Traceback (most recent call last):
  File "/worker/services/notification/__init__.py", line 178, in notify_individual_notifier
    res = await notifier.notify(comparison)
  File "/worker/services/notification/notifiers/checks/checks_with_fallback.py", line 63, in notify
    res = await self._status_notifier.notify(comparison)
  File "/worker/services/notification/notifiers/status/base.py", line 235, in notify
    return await self.send_notification(comparison, payload)
  File "/worker/services/notification/notifiers/status/base.py", line 307, in send_notification
    track_event(
  File "/usr/local/lib/python3.8/site-packages/shared/analytics_tracking/__init__.py", line 60, in track_event
    analytics.track(user_id, event_name, event_data)
  File "/usr/local/lib/python3.8/site-packages/analytics/__init__.py", line 20, in track
    _proxy('track', *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/analytics/__init__.py", line 61, in _proxy
    default_client = Client(write_key, host=host, debug=debug, on_error=on_error,
  File "/usr/local/lib/python3.8/site-packages/analytics/client.py", line 49, in __init__
    self.consumer = Consumer(self.queue, write_key, host=host, on_error=on_error,
  File "/usr/local/lib/python3.8/site-packages/analytics/consumer.py", line 65, in __init__
    self.pool = Pool(32)
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
```

We are hoping that the only upgrade causing this is `track_event` call, since other packages behaved normally on local, and this package is one that only takes effect if `segment` is enabled (which was not on local)