Adding validation to config yaml
We need to consider that, not only us, but enterprise users will put their default yamls on the 'site' config value.

So we need to validate it because they will input it in raw format.

More specifically

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 161, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 156, in _inner
    return f(*args, **kwargs)
  File "/worker/tasks/base.py", line 24, in run
    self.run_async(db_session, *args, **kwargs)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/worker/tasks/sync_pull.py", line 66, in run_async
    db_session, redis_connection, repoid=repoid, pullid=pullid, **kwargs
  File "/worker/tasks/sync_pull.py", line 173, in run_async_within_lock
    head_report.flare(changes, color=color) if head_report else None
  File "/usr/local/lib/python3.7/site-packages/covreports/reports/resources.py", line 924, in flare
    return report_to_flare(network, color, classes)
  File "/usr/local/lib/python3.7/site-packages/covreports/utils/flare.py", line 77, in report_to_flare
    if color
TypeError: coverage_to_color() takes 2 positional arguments but 8 were given
```

is caused by a not-validated config yaml